### ISSUE TITLE
[Front] 부위별 검색 페이지에서 + 버튼을 눌러도 확장이 되지 않습니다.

### ISSUE THREAD

**Issue by rasauq1122** [Dev-Dream/HealthTag#2]
Front에서 작업된 내용으로 Back에서 서버를 돌려 실제 검색이 잘 되는지 확인하는 과정에서

Front에서 구성된 부위별 검색 페이지에서 + 버튼을 눌러도 확장되지 않습니다.

마우스 커서의 모양이 바뀌지 않는 걸 보아 아예 버튼으로 인식을 안하는 것 같습니다.

**Comment by PIut0** [comment]
수정 완료했습니다
